blueprints/users/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from werkzeug.security import generate_password_hash
from models.user import User


users_blueprint = Blueprint('users', __name__, template_folder='templates/users/')

@users_blueprint.route('/')
def new():
    return render_template('registration.html')

@users_blueprint.route('/create', methods=['POST'])
def create():
    name = request.form['name']
    email = request.form['email']
    password = request.form['password']
    hashed_password = generate_password_hash(password)

    user = User(name=name, email=email, password=hashed_password)
    user.save()    

    return redirect(url_for('sessions.login'))

blueprints/users/templates/users/registration.html
{% extends 'layout.html' %}

{% block content %}
    <ion-content>
        <ion-grid>
                <ion-row>
                    <ion-col size='6' offset='3'>
                        <ion-card>
                            <ion-card-header>
                                <ion-card-title text-center>
                                    Sign Up
                                </ion-card-title>
                            </ion-card-header>
                            <ion-card-content>
                                <form action="{{ url_for('users.create') }}" method='POST'>
                                    <input type="hidden" value='{{ csrf_token() }}' name='csrf_token'>
                                    <ion-item>
                                            <ion-input placeholder='name' name='name' type='text'>
                                            </ion-input>
                                        </ion-item>
                                        <ion-item>
                                            <ion-input placeholder='email' name='email' type='email'>
                                            </ion-input>
                                        </ion-item>
                                        <ion-item>
                                            <ion-input placeholder='password' name='password' type='password'>
                                            </ion-input>
                                        </ion-item>
                                        <div text-right>
                                            <ion-button type='submit'>Submit</ion-button>
                                        </div>
                                </form>
                            </ion-card-content>
                        </ion-card>
                    </ion-col>
                </ion-row>
            </ion-grid>
    </ion-content>
{% endblock %}