blueprints/home/views.py
import os
from flask import Blueprint, render_template, url_for, request, redirect
from flask_login import login_required, current_user
from util.upload import upload_file_to_s3
from models.todo import Todo
from werkzeug.utils import secure_filename

home_blueprint = Blueprint('home', __name__, template_folder='templates/home/')


@home_blueprint.route('/')
@login_required
def show():
    user = current_user.name
    images = current_user.images
    return render_template('landing.html', user=user, images=images)


@home_blueprint.route('/upload/', methods=['POST'])
def upload_file():

    item = request.form['item']
    
	# A
    if "user_file" not in request.files:
        return "No user_file key in request.files"

	# B
    file    = request.files["user_file"]

	# C.
    if file.filename == "":
        return "Please select a file"

	# D.
    # if file and allowed_file(file.filename):
    file.filename = secure_filename(file.filename)
    output   	  = upload_file_to_s3(file, os.environ.get("S3_BUCKET"))


    url = Todo(imageUrl=output, text=item, user_id=current_user.id)
    url.save()

    return redirect(url_for('home.show'))

@home_blueprint.route('/complete', methods=['POST'])
def complete():

    imageId = request.form['imageId']

    image = Todo.get_or_none(id=imageId)
    image.is_completed = True
    image.save()

    return redirect(url_for('home.show'))

@home_blueprint.route('/delete', methods=['POST'])
def delete():

    imageId = request.form['imageId']

    image = Todo.get_or_none(id=imageId)
    image.delete_instance()
    
    return redirect(url_for('home.show'))

blueprints/home/templates/home/landing.html
{% extends 'layout.html' %}

{% block content %}


<ion-header>
    <ion-toolbar color='primary'> 
        <h1 text-center>To-go-Places</h1>
        <p text-center margin>Welcome back {{ user }}</p>
        <div text-center margin>
            <a href="{{ url_for('sessions.logout') }}">
                <ion-button color='danger'>Logout</ion-button>
            </a>
        </div>
    </ion-toolbar>
</ion-header>
<ion-content>
    <ion-grid>
        <ion-row>
            <ion-col size='6' offset='3'>
                <ion-card>
                    <ion-card-content>
                        <form action="{{ url_for('home.upload_file') }}" method='POST' enctype="multipart/form-data">
                            <ion-item>
                                <ion-input placeholder='Enter new destination..' name='item'></ion-input>
                            </ion-item>
                            <ion-item>
                                <ion-input placeholder='Upload a photo..' name='user_file' type='file'></ion-input>
                            </ion-item>
                            <ion-button type='submit' margin>Add</ion-button>
                        </form>
                    </ion-card-content>
                </ion-card>
            </ion-col>
        </ion-row>
        <ion-row>
            <ion-col size='6' offset='3'>
                <ion-card>
                    <ion-card-header>
                        <ion-card-title>Wishlist</ion-card-title>
                    </ion-card-header>
                    <ion-card-content>
                        {% for image in images %}
                        {% if image.is_completed == False %}
                        <ion-item>
                            <ion-avatar margin>
                                <img src="{{ image.imageUrl }}" alt="">
                            </ion-avatar>
                            <ion-label margin>{{ image.text }}</ion-label>
                            <form action="{{ url_for('home.complete') }}" method='POST' >
                                <input type="hidden" value='{{ csrf_token() }}' name='csrf_token'>
                                <input type="hidden" value='{{ image.id }}' name='imageId' >
                                <ion-button type='submit' color='success'>Mark as complete</ion-button>
                            </form>
                            <form action="{{ url_for('home.delete') }}" method='POST' >
                                <input type="hidden" value='{{ csrf_token() }}' name='csrf_token'>
                                <input type="hidden" value='{{ image.id }}' name='imageId' >
                                <ion-button type='submit' color='danger'>Cancel</ion-button>
                            </form>
                        </ion-item>
                        {% endif %}
                        {% endfor %}
                    </ion-card-content>
                </ion-card>
            </ion-col>
        </ion-row>
        <ion-row>
            <ion-col size='6' offset='3'>
                <ion-card>
                    <ion-card-header>
                        <ion-card-title>Completed</ion-card-title>
                    </ion-card-header>
                    <ion-card-content>
                        {% for image in images %}
                        {% if image.is_completed == True %}
                        <ion-item>
                            <ion-avatar margin>
                                <img src="{{ image.imageUrl }}" alt="">
                            </ion-avatar>
                            <ion-label margin>{{ image.text }}</ion-label>
                        </ion-item>
                        {% endif %}
                        {% endfor %}
                    </ion-card-content>
                </ion-card>
            </ion-col>
        </ion-row>
    </ion-grid>
</ion-content>


{% endblock %}